### ISSUE TITLE
还能报名吗

### ISSUE THREAD

**Issue by daisy-disc** [cubenlp/CERRU#2]

**Comment by sornkL** [comment]
已重新开放报名链接，请尽快完成报名

**Comment by sornkL** [comment]
请确认你的邮箱lang22017@qq.com是否存在

**Comment by daisy-disc** [comment]
> 请确认你的邮箱[lang22017@qq.com](mailto:lang22017@qq.com)是否存在
抱歉，填错了，lang224017@qq.com

**Comment by sornkL** [comment]
已发送邮件，请查收
